修复公告富文本
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Admin pull request #14
Opened 2022-08-18 01:52 UTC by phidiaLam

2022-08-18 03:24 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
> +        if (result.replace(/^s*|s*$/g, "") !== "") allSet = true;
这个正则 没看懂是做什么的

2022-08-18 03:24 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
> +        ];
不是说允许只有动态吗，为啥删除预测的时候强行加了个默认值

2022-08-18 03:24 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
> +          },
这个看起来像是对内容和动态都做了required验证，不像是选一个？

2022-08-18 03:38 UTC, phidiaLam commented on src/views/honeyCake/mansion/index.vue
> +        ];
这个没了就没有表单了，只能在上传的时候把上传内容删掉一下。
对吼，获取的时候也得补

2022-08-18 03:38 UTC, phidiaLam commented on src/views/honeyCake/mansion/index.vue
> +        if (result.replace(/^s*|s*$/g, "") !== "") allSet = true;
删除前后空格

2022-08-18 03:39 UTC, phidiaLam commented on src/views/honeyCake/mansion/index.vue
> +          },
确实好像这两个下面这个required可以删掉

2022-08-18 03:48 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
> +        if (result.replace(/^s*|s*$/g, "") !== "") allSet = true;
> 删除前后空格

空白符不应该是\s吗没有反斜杠的只会匹配到s这个字母吧，顺便删除前后空白符的话考虑一下直接使用trim这个方法

2022-08-18 03:52 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
> +        ];
> 这个没了就没有表单了，只能在上传的时候把上传内容删掉一下。 对吼，获取的时候也得补

可以考虑要不要弄一个`function emptyForecastItem() { return { forecast: "",   forecast_status: "unknown" }; }`来替换掉所有的这个默认值，语义可能更明确一点

2022-08-19 05:38 UTC, Yun-Shan requested changes

2022-08-19 05:38 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
> +        let result = this.mansionForm.daily[index].content.replace(this,regex, "");
`this,regex`打错了吧`this.regex`

2022-08-19 05:38 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
> +        }
考虑使用`item.info = item.info.filter(it=> !!it.forecat)`

2022-08-19 05:38 UTC, Yun-Shan commented on src/views/honeyCake/mansion/index.vue
>          ],
他俩的blur触发应该都是同时验证content和forecast，只要有一个有值就通过吧，但是现在好像是都只验证forecast

2022-08-19 05:40 UTC, phidiaLam commented on src/views/honeyCake/mansion/index.vue
> +        let result = this.mansionForm.daily[index].content.replace(this,regex, "");
啊吧啊吧

2022-08-20 10:00 UTC, Yun-Shan approved these changes
没啥问题了

2022-08-20 10:00 UTC, Yun-Shan commented on src/views/canteen/announcement/index.vue
> +        this.announcementForm.announcements[this.activeIndex].over_time == null
这个that好像没用了？

2022-08-20 10:00 UTC, Yun-Shan commented on src/views/canteen/announcement/index.vue
> +        }).finally((_) => {
js风格一般是直接`()`而不是`(_)`，不过好像全都是用的`(_)`，要么就不改要么就全都改吧

2022-08-20 10:10 UTC, phidiaLam commented on src/views/canteen/announcement/index.vue
> +        this.announcementForm.announcements[this.activeIndex].over_time == null
忘记删掉了

2022-08-20 10:10 UTC, phidiaLam commented on src/views/canteen/announcement/index.vue
> +        }).finally((_) => {
go写多了，习惯一个占位（
改掉吧

2022-08-20 10:22 UTC, Yun-Shan approved these changes

2022-08-20 10:23 UTC, merged